# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-02-24 20:21
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=200)),
                ('about_yourself', models.TextField(blank=True)),
                ('Education', models.TextField(blank=True)),
                ('Experience', models.TextField(blank=True)),
                ('skills', models.TextField(blank=True)),
                ('Work', models.TextField(blank=True)),
                ('profile_photo', models.FileField(blank=True, default='static\x07bc1.jpg', null=True, upload_to=b'')),
                ('resume', models.FileField(blank=True, null=True, upload_to=b'')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
