# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-02-28 03:05
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('register', '0003_auto_20180226_1635'),
    ]

    operations = [
        migrations.CreateModel(
            name='resource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_field', models.CharField(max_length=500)),
                ('score', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='subcategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('userid', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='subcategory',
            name='subid',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='register.subject'),
        ),
        migrations.AddField(
            model_name='resource',
            name='catid',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='register.subcategory'),
        ),
    ]
