# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-02-28 04:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0005_auto_20180228_0839'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='interest1',
            field=models.ManyToManyField(to='register.subject'),
        ),
    ]
