# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-02-28 11:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0006_profile_interest1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='resume',
            field=models.FileField(blank=True, default='static\x07bc1.jpg', upload_to=b''),
        ),
    ]
